"""add MuseumObject.frozen

Revision ID: 40e6c047955b
Revises: 109dd4123e16
Create Date: 2019-11-11 14:49:11.955578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e6c047955b'
down_revision = '109dd4123e16'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('museum_objects', sa.Column('freeze_reason', sa.Text(), nullable=True))
    op.add_column('museum_objects', sa.Column('frozen', sa.Boolean(), default=False))
    op.create_index(op.f('ix_museum_objects_frozen'), 'museum_objects', ['frozen'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_museum_objects_frozen'), table_name='museum_objects')
    op.drop_column('museum_objects', 'frozen')
    op.drop_column('museum_objects', 'freeze_reason')
    # ### end Alembic commands ###
